// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// prisma.config.ts
const dbUrl = process.env["DATABASE_URL"] || "";

// ELIMINAMOS EL BLOQUEO ESTRICTO DE NEON PARA PERMITIR SUPABASE
if (!dbUrl) {
  console.error("❌ ERROR: DATABASE_URL no está definida.");
  process.exit(1);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  // datasource no necesita 'url' aquí si ya lo pasas en el constructor de PrismaClient
});
