// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUrl = process.env["DATABASE_URL"] || "";
const directUrl = process.env["DIRECT_URL"] || "";

// Guard to prevent accidental overwrites/pushes to the wrong database
if ((dbUrl && !dbUrl.includes("wodzuelvlqontlthdlig")) || (directUrl && !directUrl.includes("wodzuelvlqontlthdlig"))) {
  console.error("❌ ERROR: DATABASE_URL does not belong to Kermingo! Execution blocked to prevent accidental overwrite.");
  process.exit(1);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: directUrl || dbUrl,
  },
});
